<h1 id="vyjimky">Výjimky
<a href="#vyjimky" class="header-link">#</a>
</h1>
<p>Pojďme si prohloubit znalosti o chybách, neboli odborně o <em>výjimkách</em>
(angl. <em>exceptions</em>).</p>
<p>Podívej se na následující funkci:</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">nacti_cislo</span><span class="p">():</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;Získá od uživatele celé číslo a vrátí ho&quot;&quot;&quot;</span>
    <span class="n">odpoved</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s1">&#39;Zadej číslo: &#39;</span><span class="p">)</span>
    <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="n">odpoved</span><span class="p">)</span>
</pre></div><p>Když uživatel nezadá číslice, ale třeba text <code>cokolada</code>,
nastane výjimka jménem <code>ValueError</code> (chyba hodnoty) a Python vypíše
odpovídající chybovou hlášku:</p>
<div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;ukazka.py&quot;</span>, line <span class="m">4</span>, in <span class="n">nacti_cislo</span>
<span class="w">    </span><span class="n">cislo</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="n">odpoved</span><span class="p">)</span>
<span class="gr">ValueError</span>: <span class="n">invalid literal for int() with base 10: &#39;cokolada&#39;</span>
</pre></div><p>Program volá funkci <code>int()</code> pro něco, co nedává smysl jako číslo.
Co s tím má chudák funkce <code>int</code> dělat?
Není žádná rozumná hodnota, kterou by mohla vrátit.
Převádění tohoto textu na celé číslo nedává smysl.</p>
<p>Až funkce <code>nacti_cislo</code> nejlíp „ví“, co se má stát, když uživatel nezadá
číslice.
Stačí se uživatele zeptat znovu!
Kdybys měl/a funkci, která zjistí, jestli jsou v řetězci jen číslice,
mohlo by to fungovat nějak takhle:</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">nacti_cislo</span><span class="p">():</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;Získá od uživatele celé číslo a vrátí ho&quot;&quot;&quot;</span>
    <span class="k">while</span> <span class="kc">True</span><span class="p">:</span>
        <span class="n">odpoved</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s1">&#39;Zadej číslo: &#39;</span><span class="p">)</span>
        <span class="k">if</span> <span class="n">obsahuje_jen_cislice</span><span class="p">(</span><span class="n">odpoved</span><span class="p">):</span>
            <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="n">odpoved</span><span class="p">)</span>  <span class="c1"># máme výsledek, funkce končí</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;To nebylo číslo!&#39;</span><span class="p">)</span>
            <span class="c1"># ... a zeptáme se znovu -- cyklus `while` pokračuje</span>
</pre></div><p>Kde ale vzít funkci <code>obsahuje_jen_cislice</code>?
Nemá smysl ji psát znovu – funkce <code>int</code> sama nejlíp pozná, co se dá převést na
číslo a co ne.
A dokonce nám to dá vědět – výjimkou, kterou můžeš <em>zachytit</em>.</p>
<div class="admonition note"><p>Ono „obsahuje_jen_cislice“ v Pythonu existuje. Dokonce několikrát.
Místo řešení problému to ale spíš ilustruje, v čem problém spočívá:</p>
<ul>
<li>Řetězcová metoda <code>isnumeric</code> vrací <code>True</code> pokud řetězec obsahuje číslice:
<code>'123'.isnumeric()</code> je pravda; <code>'abc'.isnumeric()</code> nepravda.
Problém je, že funkce <code>int</code> potřebuje jeden konkrétní druh číslic:
pro řetězce jako <code>'½'</code> nebo <code>'௩三๓໓</code>' (trojky v tamilském, japonském,
thajském a laoském písmu) platí <code>isnumeric</code>, ale <code>int</code> si na nich
vyláme zuby stejně jako na <code>'abc'</code>.</li>
<li>Řetězcová metoda <code>isdecimal</code> vrací <code>True</code> pokud řetězec obsahuje arabské
číslice 0-9. To už je lepší, ale stejně to úplně nesedí: <code>int</code> si poradí
s mezerou na začátku, např. s <code>' 3'</code>. Funkce <code>isdecimal</code> ale takový řetězec
odmítne.</li>
</ul>
<p>Chceš-li zjistit, jestli funkce <code>int</code> umí daný řetězec převést na číslo,
nejlepší je použít přímo funkci <code>int</code>.</p>
</div><h2 id="osetreni_chyby">Ošetření chyby
<a href="#osetreni_chyby" class="header-link">#</a>
</h2>
<p>Pro zachycení chyby má Python příkaz <code>try</code>/<code>except</code>.</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">nacti_cislo</span><span class="p">():</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;Získá od uživatele celé číslo a vrátí ho&quot;&quot;&quot;</span>
    <span class="k">while</span> <span class="kc">True</span><span class="p">:</span>
        <span class="n">odpoved</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s1">&#39;Zadej číslo: &#39;</span><span class="p">)</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="n">odpoved</span><span class="p">)</span>
        <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
            <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;To nebylo číslo!&#39;</span><span class="p">)</span>
            <span class="c1"># ... a zeptáme se znovu -- cyklus `while` pokračuje</span>
</pre></div><p>Jak to funguje?
Příkazy v bloku uvozeném příkazem <code>try</code> se normálně provádějí, ale když
nastane uvedená výjimka, Python přeskočí zbytek bloku <code>try</code> a provede všechno
v bloku <code>except</code>.
Pokud výjimka nenastala, přeskočí se celý blok <code>except</code>.</p>
<h2 id="druhy_chyb">Druhy chyb
<a href="#druhy_chyb" class="header-link">#</a>
</h2>
<p>A co je to <code>ValueError</code>? To je typ chyby.
Podobných typů je spousta.
Všechny jsou popsané <a href="https://docs.python.org/3/library/exceptions.html#exception-hierarchy">v dokumentaci</a>; pro nás jsou (nebo budou) důležité tyto:</p>
<div class="highlight"><pre><code>BaseException
 ├── SystemExit                     vyvolána funkcí exit()
 ├── KeyboardInterrupt              vyvolána po stisknutí Ctrl+C
 ╰── Exception
      ├── ArithmeticError
      │    ╰── ZeroDivisionError    dělení nulou
      ├── AssertionError            nepovedený příkaz `assert`
      ├── AttributeError            neexistující atribut/metoda, např. 'abc'.len
      ├── ImportError               nepovedený import
      ├── LookupError
      │    ╰── IndexError           neexistující index, např. 'abc'[999]
      ├── NameError                 použití neexistujícího jména proměnné
      │    ╰── UnboundLocalError    použití proměnné, která ještě nebyla nastavená
      ├── SyntaxError               špatná syntaxe, program je nečitelný/nepoužitelný
      │    ╰── IndentationError     špatné odsazení
      │         ╰── TabError        kombinování mezer a tabulátorů v odsazení
      ├── TypeError                 špatný typ, např. len(9)
      ╰── ValueError                špatná hodnota, např. int('xyz')
</code></pre></div><p>Tohle si není potřeba pamatovat – druh chyby, kterou je potřeba zachytit,
vždy najdeš v příslušné chybové hlášce.</p>
<p>Když odchytáváš obecnou výjimku,
chytnou se i všechny podřízené typy výjimek –
například <code>except ArithmeticError:</code> zachytí i <code>ZeroDivisionError</code>.
A <code>except Exception:</code> zachytí <em>všechny</em> výjimky, které běžně chceš zachytit.</p>
<h2 id="nechytej_je_vsechny">Nechytej je všechny!
<a href="#nechytej_je_vsechny" class="header-link">#</a>
</h2>
<p>Většinu chyb <em>není</em> potřeba ošetřovat.</p>
<p>Nastane-li <em>nečekaná</em> situace, je téměř vždy
mnohem lepší program ukončit, než se snažit
pokračovat dál a počítat se špatnými hodnotami.
Navíc chybový výstup, který Python standardně
připraví, může hodně ulehčit hledání chyby.</p>
<p>Zachytávej tedy jenom ty chyby, které <em>očekáváš</em> – víš přesně, která chyba může
nastat a proč; máš možnost správně zareagovat.</p>
<p>V našem příkladu to platí pro <code>ValueError</code> z funkce <code>int</code>: víš, že uživatel
nemusí vždy zadat číslo ve správném formátu, a víš, že správná
reakce na tuhle situaci je problém vysvětlit a zeptat se znovu.</p>
<p>Co ale dělat, když uživatel chce ukončit program a zmáčkne
<kbd>Ctrl</kbd>+<kbd>C</kbd>?
Nebo když se mu porouchá klávesnice a selže funkce <code>input</code>?
Nejlepší reakce na takovou nečekanou situaci je ukončit program a informovat
uživatele (nebo lépe, programátora), že (a kde) je něco špatně.
Neboli vypsat chybovou hlášku.
A to se stane normálně, bez <code>try</code>.</p>
<h2 id="dalsi_prilohy_kcodetrycode">Další přílohy k <code>try</code>
<a href="#dalsi_prilohy_kcodetrycode" class="header-link">#</a>
</h2>
<p>Pro úplnost: kromě <code>except</code> existují dva jiné bloky,
které můžeš „přilepit“ k <code>try</code>, a to <code>else</code> a <code>finally</code>.
První se provede, když v <code>try</code> bloku
žádná chyba nenastane; druhý se provede vždy – ať
už chyba nastala nebo ne.</p>
<p>Můžeš taky použít více bloků <code>except</code>. Provede se vždy maximálně jeden:
ten první, který danou chybu umí ošetřit.</p>
<div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">neco_udelej</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se provede, pokud nastane ValueError&#39;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">NameError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se provede, pokud nastane NameError&#39;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se provede, pokud nastane jiná chyba&#39;</span><span class="p">)</span>
    <span class="c1"># (kromě SystemExit a KeyboardInterrupt, ty chytat nechceme)</span>
<span class="k">except</span> <span class="ne">TypeError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se neprovede nikdy&#39;</span><span class="p">)</span>
    <span class="c1"># (&quot;except Exception&quot; výše ošetřuje i TypeError; sem se Python nedostane)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se provede, pokud chyba nenastane&#39;</span><span class="p">)</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se provede vždycky; i pokud v `try` bloku byl např. `return`&#39;</span><span class="p">)</span>
</pre></div><h2 id="vyvolani_chyby">Vyvolání chyby
<a href="#vyvolani_chyby" class="header-link">#</a>
</h2>
<p>Občas se stane, že výjimku budeš potřebovat vyvolat sám/sama.</p>
<p>Často se to stává, když píšeš nějakou obecnou funkci.
Třeba funkci na výpočet obsahu čtverce.
Co se stane, když někdo zavolá <code>obsah_ctverce(-5)</code>?</p>
<ul>
<li>Zadal-li ono <code>-5</code> uživatel, je potřeba mu vynadat a zeptat se znovu.</li>
<li>Naměřil-li <code>-5</code> nějaký robotický aparát, je potřeba ho líp zkalibrovat.</li>
<li>Vyšel-li čtverec se stranou <code>-5</code> v nějakém výpočtu, je nejspíš potřeba opravit
chybu v tom výpočtu.</li>
</ul>
<p>Samotná funkce <code>obsah_ctverce</code> ale „neví“, proč ji někdo volá.
Jejím úkolem je jen něco spočítat.
Měla by být použitelná ve všech případech výše – a v mnoha dalších.</p>
<p>Když někdo zavolá <code>obsah_ctverce(-5)</code>, <em>neexistuje</em> správný výsledek, který by
funkce mohla vrátit.
Místo vrácení výsledku musí tato funkce <em>signalizovat chybu</em>.
S tou se pak může program, který <code>obsah_ctverce(-5)</code> zavolal,
vypořádat – vynadat uživateli, zkalibrovat měřák, nebo, pokud na chybu není
připravený, sám skončit s chybou a upozornit tak programátora, že je něco
špatně.</p>
<p>Jak na to prakticky?
Chybu můžeš vyvolat pomocí příkazu <code>raise</code>.
Za příkaz dáš druh výjimky a pak do závorek nějaký popis toho, co je špatně.</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">obsah_ctverce</span><span class="p">(</span><span class="n">strana</span><span class="p">):</span>
<span class="w">    </span><span class="sd">&quot;&quot;&quot;Vrátí obsah čtverce s danou délkou strany&quot;&quot;&quot;</span>
    <span class="k">if</span> <span class="n">strana</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">strana</span> <span class="o">**</span> <span class="mi">2</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="sa">f</span><span class="s1">&#39;Strana musí být kladná, číslo </span><span class="si">{</span><span class="n">strana</span><span class="si">}</span><span class="s1"> kladné není!&#39;</span><span class="p">)</span>
</pre></div><p>Podobně jako <code>return</code> i příkaz <code>raise</code> ukončí funkci.
A nejen tu – pokud na tuhle konkrétní chybu není program předem připravený,
ukončí se celý program.</p>
<p>Ze začátku není u <code>raise</code> příliš důležité dumat nad tím, který typ výjimky je
ten správný.
Klidně „střílej od boku“.
<code>ValueError</code> bývá často správná volba.</p>